baseURL = 'https://timihuyu.github.io/lannews/'
languageCode = 'en-us'
publishDir="docs"
theme = 'ananke'
canonifyurls = true
title = '生命在于运动'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true